name: "ssh-job"
description: "Execute any script through ssh"
author: "Marcin Jałocha"
inputs:
  host:
    required: true
    description: "Target machine hostname or ip"
  port:
    required: true
    description: "Port to use while connecting"
    default: "22"
  key:
    description: "Ssh private key used to connect to target machine"
  user:
    description: "Ssh user"
  password:
    description: "Ssh password"
  envs:
    description: "Environment variables passed to the shell script"
  ignoredEnvs:
    description: "Environment variables that are ommited from passing to the shell"
  command:
    required: true
    description: "Bash commands ran on target machine"

runs:
  using: "node16"
  main: "dist/index.js"
